# Generated by Django 3.2.20 on 2023-07-13 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('school', '0001_initial'),
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachermodel',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistic.subjectmodel'),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='clasS',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.classmodel'),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='parents',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.parentsmodel'),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.schoolmodel'),
        ),
    ]
